version: '1.0.0'
services:
  apiPrivateCandidat:
    image: api-private-candidat:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - api_private

networks:
  api_private:
    driver: bridge